"""
Django settings for _crm_system project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

print("BASE_DIR:", BASE_DIR)




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^#opt8hk2+7k$idupqc=9q_!)&cjn!a5ilwxn72ab0)u)pjxy*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['192.168.137.1']
ALLOWED_HOSTS = ['localhost', '192.168.18.74', '127.0.0.1', '*']




# Application definition

INSTALLED_APPS = [
    "djangocms_admin_style",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'email_handler',
    'corsheaders',
    'django_celery_beat',
    'django_celery_results',
    'users',
    'customers',
    'whatsapp_handler',
    'tasks',
    'faqs',
    'ai_integration',
    'analytics',
    'integrations',
    'tasks_handler',
    'frontend',
    'drf_yasg'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = '_crm_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [BASE_DIR / 'templates', os.path.join(BASE_DIR, 'web', 'build')],
        'DIRS': [os.path.join(BASE_DIR, 'web', 'build')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = '_crm_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'sql_server.pyodbc',  # updated engine for SQL Server
#         'NAME': 'crm_system_db',  # Replace with your SQL Server database name
#         'USER': '',  # Replace with your SQL Server username
#         'PASSWORD': '',  # Replace with your SQL Server password
#         'HOST': r'DESKTOP-AR77EUE\SQLEXPRESS',  # Replace with your SQL Server host
#         'PORT': '1433',  # Default SQL Server port; update if needed
#         'OPTIONS': {
#             'driver': 'ODBC Driver 17 for SQL Server',  # Ensure driver is installed
#         },
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Karachi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'


# Configure static files for custom admin branding
STATICFILES_DIRS = [
    BASE_DIR / "static",
    os.path.join(BASE_DIR, 'web', 'build', 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS configuration
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',  # Existing frontend URL
    'http://localhost:3001',  # Add this frontend URL
    'http://192.168.137.90:3001',
    "http://localhost:3000",
    "http://192.168.18.74:3000"
]

# Optionally, allow all origins (not recommended for production)
# CORS_ALLOW_ALL_ORIGINS = True

# Ensure CORS headers are included in responses
CORS_ALLOW_CREDENTIALS = True

# Celery settings
CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Redis as the message broker
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_BACKEND = 'django-db' 
# Celery Configuration Options
CELERY_TIMEZONE = "Asia/Karachi"
CELERY_TASK_TRACK_STARTED = True
# CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # Grace period before hard kill

CELERY_BEAT_SCHEDULE = {
    'fetch-unread-emails-every-minute': {
        'task': 'email_handler.tasks.fetch_unread_emails_task',  # Full path to the task function
        'schedule': timedelta(minutes=1),  # Execute every 1 minute
    },
    'fetch-whatsapp-messages-every-minute': {
        'task': 'whatsapp_handler.tasks.fetch_whatsapp_messages_task',  # Full path to the WhatsApp task
        'schedule': timedelta(minutes=1),  # Execute every 1 minute
    },
}


# WhatsApp API Settings
WAAPI_API_KEY = os.getenv('WAAPI_API_KEY')
WAAPI_BASE_URL = os.getenv('WAAPI_BASE_URL', 'https://whatsapp.maxremind.com/api/v1')
WAAPI_TIMEOUT = int(os.getenv('WAAPI_TIMEOUT', '30'))
WAAPI_SSL_VERIFY = os.getenv('WAAPI_SSL_VERIFY', 'True').lower() == 'true'
WAAPI_TEST_MODE = os.getenv('WAAPI_TEST_MODE', 'True').lower() == 'true'  # Add this line


CMS_ENABLE_UPDATE_CHECK = True
CMS_UPDATE_CHECK_TYPE = ('patch')




MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


AI_RESPONSE = True
API_HOST='github'
AI_MODEL_NAME = 'gpt-4o'
AI_MAX_TOKENS = 1000



WAAPI_SSL_VERIFY = True  # Set to False only in development if needed
WAAPI_TIMEOUT = 30  # seconds

