# Generated by Django 5.1.7 on 2025-05-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_integration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("model_name", models.CharField(max_length=100)),
                ("prompt_tokens", models.IntegerField()),
                ("completion_tokens", models.IntegerField()),
                ("total_tokens", models.IntegerField()),
                ("source", models.CharField(default="unknown", max_length=50)),
            ],
        ),
    ]
