# Generated by Django 5.1.7 on 2025-04-29 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_handler", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="whatsapp_query",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="email_handler.whatsappmessage",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="email_query",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="email_handler.emailquery",
            ),
        ),
    ]
