# Generated by Django 5.1.7 on 2025-05-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_handler", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailquery",
            name="outlook_message_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="emailquery",
            name="gmail_thread_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
