# Generated by Django 5.1.7 on 2025-04-14 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_handler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('received_at', models.DateTimeField()),
                ('is_replied', models.BooleanField(default=False)),
                ('whatsapp_message_id', models.CharField(max_length=255, unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_handler.customer')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('whatsapp_message_id', models.CharField(max_length=255, unique=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='email_handler.whatsappmessage')),
            ],
        ),
    ]
