# Generated by Django 5.1.7 on 2025-04-14 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_handler', '0002_whatsappmessage_whatsappreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='alternate_phone',
            field=models.CharField(blank=True, help_text='Alternative contact number', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, help_text='WhatsApp or primary contact number with country code (e.g. +1234567890)', max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_contact',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('phone', 'Phone')], default='email', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone_number'], name='email_handl_phone_n_05a8bb_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='email_handl_email_a0ded4_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('email__isnull', False), ('phone_number__isnull', False), _connector='OR'), name='customer_must_have_contact'),
        ),
    ]
