# Generated by Django 5.1.7 on 2025-05-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_handler", "0002_task_whatsapp_query_alter_task_email_query"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailquery",
            name="gmail_message_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="emailreply",
            name="in_reply_to",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="emailreply",
            name="references",
            field=models.TextField(blank=True, null=True),
        ),
    ]
