# Generated by Django 5.1.7 on 2025-05-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_handler", "0002_emailquery_outlook_message_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailquery",
            name="gmail_message_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
