# Generated by Django 5.1.7 on 2025-05-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_handler", "0003_emailquery_gmail_message_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailreply",
            name="outlook_message_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="emailreply",
            name="gmail_message_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
