# Generated by Django 5.1.7 on 2025-05-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_handler", "0004_emailreply_outlook_message_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailreply",
            name="source",
            field=models.TextField(null=True),
        ),
    ]
