# Generated by Django 5.1.7 on 2025-05-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_handler", "0005_emailreply_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailreply",
            name="source",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
