# Generated by Django 5.1.7 on 2025-05-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_handler", "0006_alter_emailreply_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailquery",
            name="source",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
