# Generated by Django 5.1.7 on 2025-05-14 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("email_handler", "0007_emailquery_source"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailquery",
            old_name="source",
            new_name="email_source",
        ),
    ]
