def generate_whatsapp_reply_prompt(customer_name, last_message):
    return (
        f"You're a helpful, friendly assistant. Write a warm, professional, and clear automated reply "
        f"to a customer message. Address the customer by their name: {customer_name}. "
        f"Here is the customer's message: '{last_message}'\n\n"
        "End the message with:\nAI Mutti\nMaxRemind"
    )


def generate_email_reply_prompt(thread_context, email_body, customer_name):
    return (
        "You are AI Mutti, a friendly and professional assistant from MaxRemind. "
        "Customer name is " + customer_name + ". "
        "Your job is to generate well-written, polite, and helpful email replies. "
        "Respond to the following email in a clear, concise, and respectful tone. "
        "Keep the language simple, professional, and approachable—neither too formal nor too casual. "
        "Always make the sender feel acknowledged, understood, and supported. "
        "Make sure the reply sounds human, empathetic, and solution-oriented. "
        "Avoid robotic phrasing or overly complex language. "
        "Here is the email thread context:\n\"\"\"\n" + thread_context + "\n\"\"\"\n"
        "Here is the latest email content:\n\"\"\"\n" + email_body + "\n\"\"\"\n"
        "Write a well-formatted and thoughtful reply. Wrap the reply in the following HTML template:\n"
        "<!DOCTYPE html>"
        "<html>"
        "<head>"
        "<meta name='viewport' content='width=device-width, initial-scale=1'>"
        "<style>"
        "body { "
        "    font-family: 'Segoe UI', system-ui, -apple-system, sans-serif; "
        "    line-height: 1.6; "
        "    color: #2d3748; "
        "    margin: 0;"
        "    background-color: #f7fafc;"
        "}"
        ".header { "
        "    background-color: #ffffff;"
        "    padding: 2rem 1rem;"
        "    text-align: center;"
        "    box-shadow: 0 2px 4px rgba(0,0,0,0.1);"
        "}"
        ".logo {"
       " display: block;"
   " height: auto;"
   " max-height: 60px;"
    "max-width: 240px;"
  "  width: auto;"
    "margin: 0 auto;"
    "object-fit: contain;"
        "}"
        ".content { "
        "    max-width: 800px;"
        "    margin: 2rem auto;"
        "    padding: 2rem;"
        "    background: white;"
        "    border-radius: 8px;"
        "    box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);"
        "}"
        ".footer { "
        "    text-align: center;"
        "    padding: 2rem 1rem;"
        "    color: #718096;"
        "    font-size: 0.875rem;"
        "    border-top: 1px solid #e2e8f0;"
        "    margin-top: 2rem;"
        "}"
        "a {"
        "    color: #2171b5;"
        "    text-decoration: none;"
        "    font-weight: 500;"
        "}"
        "a:hover {"
        "    text-decoration: underline;"
        "}"
        "@media (max-width: 640px) {"
        "    .content {"
        "        margin: 1rem;"
        "        padding: 1.5rem;"
        "    }"
        "    .header {"
        "        padding: 1.5rem 1rem;"
        "    }"
        "}"
        "</style>"
        "</head>"
        "<body>"
        "<div class='header'>"
        "<img src='https://maxremind.com/wp-content/uploads/2024/07/Maxremind-HD-Logo-min-1536x271.png' "
        "     alt='MaxRemind Logo' "
        "     class='logo'>"
        "</div>"
        "<div class='content'>"
        "{reply_body}"
        "</div>"
        "<div class='footer'>"
        "© 2024 MaxRemind. All rights reserved.<br>"
        "<span style='font-size: 0.75rem; color: #a0aec0;'>Need help? Contact our support team</span>"
        "</div>"
        "</body>"
        "</html>"
    )
